name: Bake and Serve

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
      
    # Install and build your Angular App
    - name: Install Packages
      run: npm install

    - name: Build Angular
      run: npm run build

    - name: Apply stash
      run: git stash apply

    # Deploy to Azure Blob Storage
    - name: Upload to Azure Blob Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name rotatoproduction --auth-mode key --overwrite -d '$web' -s /dist/rotato-ui
      
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
          inlineScript: |
             az cdn endpoint purge --content-paths  "/*" --profile-name "rotatoCDN" --name "rotato" --resource-group "rotato-prod"

  # Azure logout
    - name: logout
      run: |
          az logout
      if: always()
